"""
50 curated job listings with unique descriptions.
All job skills are validated against the master skills dictionary.
"""

from datetime import timedelta
from app.skills_dictionary import SKILLS_LOWER

# Remap non-standard skill names to dictionary entries
_REMAP = {
    'spark': 'Apache Spark', 'excel': 'Data Analysis', 'a/b testing': 'Analytics',
    'performance optimization': 'Low Latency', 'rest': 'REST APIs', 'databases': 'SQL',
    'core data': 'iOS', 'healthkit': 'iOS', 'mathematics': 'Statistics',
    'junit': 'Unit Testing', 'maven': 'Java', 'sap abap': 'Java', 'sap hana': 'SQL',
    'fiori': 'React', 'odata': 'REST APIs', 'rfc': 'API Design', 'bapi': 'API Design',
    'alv reports': 'Data Visualization', 'mvvm': 'Android', 'coroutines': 'Kotlin',
    'dagger/hilt': 'Android', 'room db': 'SQLite', 'spring': 'Spring Boot',
    'express': 'Express.js', 'testing': 'Unit Testing', 'automation': 'CI/CD',
    'debugging': 'System Design', 'performance': 'Low Latency',
    'performance tuning': 'Low Latency', 'storage': 'Distributed Systems',
    'storage systems': 'Distributed Systems', 'file systems': 'Operating Systems',
    'linux kernel': 'Linux', 'android aosp': 'Android', 'messaging systems': 'Kafka',
    'cloud strategy': 'AWS', 'cloud computing': 'AWS', 'product thinking': 'Product Strategy',
    'powerbi': 'Power BI', 'web vitals': 'React', 'css-in-js': 'CSS',
    'design systems': 'React', 'aws mediaservices': 'AWS', 'webrtc': 'WebSockets',
    'websocket': 'WebSockets', 'ffmpeg': 'Python', 'hls/dash': 'Networking',
    'cdn': 'Networking', 'information retrieval': 'NLP', 'image processing': 'Computer Vision',
    'gans': 'Deep Learning', 'linear algebra': 'Statistics',
    'functional programming': 'Haskell', 'opencv': 'Computer Vision',
    'cuda': 'C++', 'gpu programming': 'C++', 'llvm': 'C++', 'compiler design': 'C++',
    'postgis': 'PostgreSQL', 'sdn': 'Networking', 'paxos/raft': 'Distributed Systems',
    'google analytics': 'Analytics', 'quantitative finance': 'Quantitative Analysis',
    'fixed income': 'Financial Modeling', 'risk modeling': 'Risk Management',
    '5g/lte': 'Networking', 'dsp': 'Embedded Systems', 'x86 architecture': 'ARM Architecture',
    'yang models': 'Networking', 'vsphere': 'Kubernetes',
    'high concurrency': 'Concurrency', 'accessibility': 'React',
    'assembly': 'C', 'business analysis': 'Analytics', 'memory management': 'C++',
    'optimization': 'Algorithms', 'pwa': 'React', 'stochastic calculus': 'Statistics',
    'tcp/ip': 'Networking', 'user research': 'Product Strategy', 'wireframing': 'Figma',
}


def _normalize_skills(skills):
    """Ensure all skills are from the master dictionary."""
    result = []
    seen = set()
    for s in skills:
        if s.lower() in SKILLS_LOWER:
            canonical = SKILLS_LOWER[s.lower()]
        elif s.lower() in _REMAP:
            canonical = _REMAP[s.lower()]
        else:
            continue
        if canonical.lower() not in seen:
            seen.add(canonical.lower())
            result.append(canonical)
    return result[:8]


def get_all_jobs(today):
    jobs = _raw_jobs(today)
    for j in jobs:
        j["skills"] = _normalize_skills(j["skills"])
    return jobs


def _raw_jobs(today):
    return [
        {"company": "Google", "role": "Software Engineer - Cloud Infrastructure", "domain": "Software", "location": "Bangalore", "salary": "₹15-20 LPA", "job_type": "Full-time", "skills": ["Python", "Go", "Kubernetes", "Docker", "System Design", "Distributed Systems", "gRPC", "Linux"], "last_date_to_apply": today + timedelta(days=10), "description": "Build and operate Google Cloud Platform's core compute stack. Design fault-tolerant distributed systems handling millions of RPS. Write performance-critical Go and Python, operate Kubernetes clusters at scale.", "eligibility": "B.Tech/M.Tech CS/IT, 7+ CGPA", "responsibilities": ["Design horizontally scalable microservices", "Own full lifecycle from design to production", "Optimize p99 latency under 50ms", "Lead incident response"], "benefits": ["₹15-20 LPA + RSUs", "Health insurance", "20% time for projects", "₹2L learning budget"], "about_company": "Google Cloud serves millions of organizations worldwide."},
        {"company": "Microsoft", "role": "Product Manager - Azure DevOps", "domain": "Product", "location": "Pune", "salary": "₹18-25 LPA", "job_type": "Full-time", "skills": ["Product Strategy", "SQL", "Analytics", "Leadership", "Agile", "Communication", "Data Analysis"], "last_date_to_apply": today + timedelta(days=15), "description": "Own the CI/CD pipeline experience for 500K+ dev teams. Synthesize customer research and telemetry into product roadmap. Make scope tradeoffs daily with engineering.", "eligibility": "Any engineering degree, 2+ years PM experience", "responsibilities": ["Own Azure Pipelines roadmap", "Run weekly customer calls", "Define success metrics", "Write clear PRDs"], "benefits": ["₹18-25 LPA + bonus", "ESPP 15% discount", "30 days PTO", "MBA sponsorship"], "about_company": "Microsoft Azure is the world's second-largest cloud."},
        {"company": "Amazon", "role": "Data Analyst - Supply Chain", "domain": "Data", "location": "Hyderabad", "salary": "₹10-15 LPA", "job_type": "Full-time", "skills": ["SQL", "Python", "Excel", "Tableau", "Statistics", "Data Analysis", "ETL", "Pandas"], "last_date_to_apply": today + timedelta(days=5), "description": "Analyze 12 billion packages across 185 fulfillment centers. Build Tableau dashboards, write complex Redshift queries, develop Python ETL pipelines for supply chain optimization.", "eligibility": "B.Tech/M.Tech any stream, 6.5+ CGPA", "responsibilities": ["Build 15+ dashboards", "Optimize SQL on 500M+ rows", "Develop ETL pipelines", "Present to leadership"], "benefits": ["₹10-15 LPA", "₹1.5L sign-on", "Health insurance", "Transfer to ML roles"], "about_company": "Amazon delivers to 100+ countries."},
        {"company": "Flipkart", "role": "Full Stack Engineering Intern", "domain": "Software", "location": "Bangalore", "salary": "₹50,000/month", "job_type": "Internship", "skills": ["React", "Node.js", "MongoDB", "JavaScript", "HTML", "CSS", "Git", "REST"], "last_date_to_apply": today + timedelta(days=3), "description": "6-month internship for 400M users. Ship production code, build features end-to-end. Past interns built Similar Products widget and order tracking redesign.", "eligibility": "B.Tech 3rd/4th year CS/IT", "responsibilities": ["Build end-to-end features", "Write Jest tests", "Daily standups", "Monthly presentations"], "benefits": ["₹50K/month", "PPO ₹18-24 LPA", "Free meals", "MacBook provided"], "about_company": "India's largest e-commerce, 10M orders/day during sales."},
        {"company": "Meta", "role": "Backend Engineer - Messaging", "domain": "Software", "location": "Delhi", "salary": "₹25-35 LPA", "job_type": "Full-time", "skills": ["C++", "Python", "Distributed Systems", "Databases", "API Design", "System Design", "Linux", "Networking"], "last_date_to_apply": today + timedelta(days=2), "description": "Build systems delivering 100B messages/day across WhatsApp, Messenger, Instagram DMs. Ensure exactly-once delivery, sub-second replication across continents.", "eligibility": "B.Tech/M.Tech CS, 7.5+ CGPA", "responsibilities": ["Design 10M+ writes/sec storage", "Optimize p99 < 500ms globally", "Build chaos tools", "Open-source contributions"], "benefits": ["₹25-35 LPA + RSUs", "15-25% bonus", "Unlimited PTO", "₹5L wellness"], "about_company": "Meta messaging connects 3 billion people."},
        {"company": "Apple", "role": "iOS Developer - Health & Fitness", "domain": "Software", "location": "Mumbai", "salary": "₹22-28 LPA", "job_type": "Full-time", "skills": ["Swift", "iOS", "UIKit", "SwiftUI", "Core Data", "Xcode", "HealthKit", "Objective-C"], "last_date_to_apply": today + timedelta(days=20), "description": "Build health monitoring for Apple Watch/iPhone. HealthKit, CoreMotion, sensor fusion. All on-device processing for privacy. Features that have literally saved lives.", "eligibility": "B.Tech/M.Tech CS/IT, 7+ CGPA", "responsibilities": ["Implement HealthKit features", "Build SwiftUI interfaces", "Optimize battery < 2%", "90%+ test coverage"], "benefits": ["₹22-28 LPA + RSUs", "25% Apple discount", "₹3L education", "Fitness center"], "about_company": "Apple Health used by 150M people."},
        {"company": "Goldman Sachs", "role": "Quantitative Strategist", "domain": "Finance", "location": "Bangalore", "salary": "₹20-28 LPA", "job_type": "Full-time", "skills": ["Python", "C++", "Statistics", "Machine Learning", "Financial Modeling", "Mathematics", "R"], "last_date_to_apply": today + timedelta(days=8), "description": "Price exotic options, calculate Greeks, generate hedging strategies for $50B portfolio. Stochastic calculus meets high-performance C++ meets Python tooling.", "eligibility": "B.Tech/M.Tech strong math, 8+ CGPA", "responsibilities": ["Develop pricing models", "C++ engines sub-ms latency", "Python calibration tools", "Present to risk committees"], "benefits": ["₹20-28 LPA + 30-80% bonus", "Stock plan", "CFA sponsorship", "Global rotation"], "about_company": "Leading global investment bank."},
        {"company": "TCS", "role": "Java Developer - Banking Solutions", "domain": "Software", "location": "Mumbai", "salary": "₹6-9 LPA", "job_type": "Full-time", "skills": ["Java", "Spring Boot", "Microservices", "Oracle DB", "REST APIs", "JUnit", "Maven"], "last_date_to_apply": today + timedelta(days=12), "description": "Develop core banking modules serving 200+ financial institutions. Build transaction processing systems handling 50K TPS with zero downtime deployments.", "eligibility": "B.Tech/M.Tech CS/IT, 6+ CGPA", "responsibilities": ["Develop Spring Boot microservices", "Write integration tests", "Participate in code reviews", "Support production releases"], "benefits": ["₹6-9 LPA", "Health insurance family", "Learning platforms access", "Onsite opportunities"], "about_company": "TCS is India's largest IT services company serving clients in 150+ countries."},
        {"company": "Infosys", "role": "Data Engineer - Cloud Migration", "domain": "Data", "location": "Pune", "salary": "₹8-12 LPA", "job_type": "Full-time", "skills": ["Python", "Apache Spark", "AWS", "SQL", "Airflow", "Kafka", "Hadoop", "Scala"], "last_date_to_apply": today + timedelta(days=14), "description": "Migrate legacy data warehouses to cloud-native architectures for Fortune 500 clients. Design Spark pipelines processing 10TB+ daily with Airflow orchestration.", "eligibility": "B.Tech/M.Tech CS/IT/ECE, 6.5+ CGPA", "responsibilities": ["Build Spark ETL pipelines", "Design data lake architectures", "Automate with Airflow DAGs", "Optimize query performance"], "benefits": ["₹8-12 LPA", "AWS certification sponsored", "Flexible work", "Annual bonus"], "about_company": "Infosys is a global leader in next-generation digital services and consulting."},
        {"company": "Wipro", "role": "DevOps Engineer", "domain": "Software", "location": "Hyderabad", "salary": "₹7-11 LPA", "job_type": "Full-time", "skills": ["Docker", "Kubernetes", "Jenkins", "Terraform", "AWS", "Linux", "Python", "Ansible"], "last_date_to_apply": today + timedelta(days=18), "description": "Automate infrastructure provisioning and CI/CD pipelines for enterprise clients. Manage Kubernetes clusters across multi-cloud environments with 99.99% uptime SLAs.", "eligibility": "B.Tech CS/IT/ECE, 6+ CGPA", "responsibilities": ["Manage K8s clusters", "Build CI/CD pipelines", "Implement IaC with Terraform", "Monitor with Prometheus/Grafana"], "benefits": ["₹7-11 LPA", "Cloud certifications", "Remote work options", "Health coverage"], "about_company": "Wipro is a leading technology services company with operations in 66 countries."},
        {"company": "HCL", "role": "SAP ABAP Consultant", "domain": "Core", "location": "Noida", "salary": "₹9-14 LPA", "job_type": "Full-time", "skills": ["SAP ABAP", "SAP HANA", "FIORI", "OData", "RFC", "BAPI", "ALV Reports"], "last_date_to_apply": today + timedelta(days=10), "description": "Implement SAP S/4HANA solutions for manufacturing and retail clients. Develop custom ABAP programs, FIORI apps, and CDS views for real-time analytics.", "eligibility": "B.Tech/MBA with SAP certification preferred", "responsibilities": ["Develop ABAP custom programs", "Build FIORI applications", "Create CDS views", "Support go-live activities"], "benefits": ["₹9-14 LPA", "SAP certification funded", "Global travel", "Performance bonus"], "about_company": "HCL Technologies is a multinational IT services company headquartered in Noida."},
        {"company": "Razorpay", "role": "Backend Engineer - Payments", "domain": "Software", "location": "Bangalore", "salary": "₹18-26 LPA", "job_type": "Full-time", "skills": ["Go", "Python", "PostgreSQL", "Redis", "Kafka", "System Design", "Docker", "AWS"], "last_date_to_apply": today + timedelta(days=7), "description": "Build payment infrastructure processing ₹7 lakh crore annually. Design idempotent APIs, implement distributed transactions, and ensure PCI-DSS compliance at scale.", "eligibility": "B.Tech/M.Tech CS, 7+ CGPA", "responsibilities": ["Design payment APIs", "Implement distributed transactions", "Ensure PCI compliance", "Handle 10K+ TPS"], "benefits": ["₹18-26 LPA + ESOPs", "Health insurance", "Learning budget ₹1L", "Flexible hours"], "about_company": "Razorpay powers payments for 8M+ businesses in India."},
        {"company": "PhonePe", "role": "Android Developer", "domain": "Software", "location": "Bangalore", "salary": "₹16-22 LPA", "job_type": "Full-time", "skills": ["Kotlin", "Android", "MVVM", "Jetpack Compose", "Coroutines", "Dagger/Hilt", "Room DB"], "last_date_to_apply": today + timedelta(days=9), "description": "Build features for India's most-used UPI app with 450M+ registered users. Optimize app startup time, reduce ANRs, and deliver pixel-perfect UI experiences.", "eligibility": "B.Tech/M.Tech CS/IT, 7+ CGPA", "responsibilities": ["Develop Jetpack Compose UIs", "Optimize app performance", "Write unit and UI tests", "Reduce crash rates"], "benefits": ["₹16-22 LPA + ESOPs", "Health insurance", "Gym membership", "Annual retreats"], "about_company": "PhonePe is India's leading digital payments platform with 450M+ users."},
        {"company": "Swiggy", "role": "Machine Learning Engineer - Recommendations", "domain": "Data", "location": "Bangalore", "salary": "₹20-30 LPA", "job_type": "Full-time", "skills": ["Python", "TensorFlow", "PyTorch", "SQL", "Spark", "MLOps", "Deep Learning", "NLP"], "last_date_to_apply": today + timedelta(days=11), "description": "Build recommendation systems serving 50M+ monthly users. Design real-time ML pipelines for restaurant ranking, personalized feeds, and delivery time prediction.", "eligibility": "M.Tech/PhD in CS/ML/Statistics", "responsibilities": ["Build recommendation models", "Deploy ML pipelines", "Run A/B experiments", "Improve CTR by 10%+"], "benefits": ["₹20-30 LPA + ESOPs", "Free Swiggy One", "Health insurance", "Learning conferences"], "about_company": "Swiggy is India's leading on-demand delivery platform."},
        {"company": "Zomato", "role": "Product Manager - Dining Out", "domain": "Product", "location": "Gurgaon", "salary": "₹22-30 LPA", "job_type": "Full-time", "skills": ["Product Strategy", "SQL", "A/B Testing", "User Research", "Analytics", "Wireframing", "Communication"], "last_date_to_apply": today + timedelta(days=13), "description": "Own the dining-out experience for 15M+ monthly diners. Drive table reservation features, restaurant discovery, and loyalty programs across 800+ cities.", "eligibility": "B.Tech + MBA preferred, 3+ years PM experience", "responsibilities": ["Define product roadmap", "Analyze user funnels", "Coordinate with engineering", "Launch new city features"], "benefits": ["₹22-30 LPA + ESOPs", "Free Zomato Gold", "Flexible work", "Annual offsite"], "about_company": "Zomato connects millions of users to restaurants across India."},
        {"company": "Paytm", "role": "Frontend Engineer - Payments Dashboard", "domain": "Software", "location": "Noida", "salary": "₹12-18 LPA", "job_type": "Full-time", "skills": ["React", "TypeScript", "Redux", "GraphQL", "Jest", "Webpack", "CSS-in-JS"], "last_date_to_apply": today + timedelta(days=6), "description": "Build merchant-facing dashboards handling ₹4 lakh crore in transactions. Create real-time analytics views, settlement reports, and payment link generators used by 30M+ merchants.", "eligibility": "B.Tech/M.Tech CS/IT, 6.5+ CGPA", "responsibilities": ["Build React dashboard components", "Implement real-time data views", "Optimize bundle size", "Write comprehensive tests"], "benefits": ["₹12-18 LPA + ESOPs", "Health insurance", "Paytm wallet credits", "Flexible hours"], "about_company": "Paytm is India's leading fintech company with 300M+ users."},
        {"company": "CRED", "role": "Backend Engineer - Rewards Platform", "domain": "Software", "location": "Bangalore", "salary": "₹25-35 LPA", "job_type": "Full-time", "skills": ["Java", "Spring Boot", "PostgreSQL", "Redis", "Kafka", "System Design", "AWS", "Microservices"], "last_date_to_apply": today + timedelta(days=15), "description": "Design the rewards and cashback engine for India's most premium fintech app. Build event-driven systems processing millions of credit card transactions with real-time reward calculations.", "eligibility": "B.Tech/M.Tech CS, 7.5+ CGPA, 3+ years experience", "responsibilities": ["Design event-driven architecture", "Build rewards calculation engine", "Ensure 99.99% uptime", "Mentor junior engineers"], "benefits": ["₹25-35 LPA + ESOPs", "Premium health insurance", "₹2L wellness budget", "Top-tier office amenities"], "about_company": "CRED is a fintech platform for creditworthy individuals with 20M+ members."},
        {"company": "Zerodha", "role": "Systems Programmer - Trading Engine", "domain": "Core", "location": "Bangalore", "salary": "₹20-30 LPA", "job_type": "Full-time", "skills": ["Go", "C", "Linux", "Networking", "Low Latency", "System Design", "PostgreSQL"], "last_date_to_apply": today + timedelta(days=16), "description": "Build India's largest retail trading platform handling 15M+ orders daily. Optimize order matching to sub-millisecond latency with zero message loss guarantees.", "eligibility": "B.Tech/M.Tech CS, strong systems fundamentals", "responsibilities": ["Optimize trading engine latency", "Build network protocols", "Design failover systems", "Profile and tune performance"], "benefits": ["₹20-30 LPA + profit sharing", "No hierarchy culture", "Remote-first", "₹3L learning budget"], "about_company": "Zerodha is India's largest stock broker with 10M+ active clients."},
        {"company": "Groww", "role": "Data Scientist - Risk Analytics", "domain": "Data", "location": "Bangalore", "salary": "₹16-24 LPA", "job_type": "Full-time", "skills": ["Python", "SQL", "Machine Learning", "Statistics", "Pandas", "Scikit-learn", "Risk Modeling"], "last_date_to_apply": today + timedelta(days=8), "description": "Build credit risk models and fraud detection systems for India's fastest-growing investment platform. Analyze user behavior patterns across 8M+ investors to prevent financial fraud.", "eligibility": "B.Tech/M.Tech with strong statistics background", "responsibilities": ["Build fraud detection models", "Analyze transaction patterns", "Create risk scorecards", "Present findings to leadership"], "benefits": ["₹16-24 LPA + ESOPs", "Health insurance", "Stock investing credits", "Flexible work"], "about_company": "Groww is India's leading investment platform with 8M+ active investors."},
        {"company": "Ola", "role": "Backend Engineer - Maps & Navigation", "domain": "Software", "location": "Bangalore", "salary": "₹14-20 LPA", "job_type": "Full-time", "skills": ["Python", "Go", "PostgreSQL", "PostGIS", "Redis", "Kafka", "Docker", "Algorithms"], "last_date_to_apply": today + timedelta(days=10), "description": "Build Ola Maps powering navigation for millions of daily rides. Develop real-time routing algorithms, ETA prediction models, and geospatial indexing systems.", "eligibility": "B.Tech/M.Tech CS/IT, 7+ CGPA", "responsibilities": ["Develop routing algorithms", "Optimize ETA predictions", "Build geospatial indexes", "Handle 1M+ concurrent requests"], "benefits": ["₹14-20 LPA + ESOPs", "Ola ride credits", "Health insurance", "Gym membership"], "about_company": "Ola is India's largest mobility platform operating in 250+ cities."},
        {"company": "Uber India", "role": "Software Engineering Intern - Marketplace", "domain": "Software", "location": "Hyderabad", "salary": "₹80,000/month", "job_type": "Internship", "skills": ["Java", "Go", "SQL", "Data Structures", "Algorithms", "Git", "REST APIs"], "last_date_to_apply": today + timedelta(days=4), "description": "6-month internship working on Uber's marketplace matching algorithms. Contribute to systems that match 25M+ rides daily with optimal driver-rider pairing.", "eligibility": "B.Tech 3rd/4th year CS/IT, 7.5+ CGPA", "responsibilities": ["Implement matching features", "Write unit tests", "Participate in design reviews", "Present intern project"], "benefits": ["₹80K/month", "PPO ₹22-28 LPA", "Uber credits", "Mentorship program"], "about_company": "Uber India Engineering is one of Uber's largest engineering hubs globally."},
        {"company": "Atlassian", "role": "Senior Frontend Engineer - Jira", "domain": "Software", "location": "Bangalore", "salary": "₹30-42 LPA", "job_type": "Full-time", "skills": ["React", "TypeScript", "GraphQL", "Performance Optimization", "Accessibility", "Design Systems", "Testing"], "last_date_to_apply": today + timedelta(days=20), "description": "Build the next generation of Jira used by 250K+ organizations. Lead performance optimization initiatives, implement accessible components, and mentor frontend engineers.", "eligibility": "B.Tech/M.Tech CS, 5+ years frontend experience", "responsibilities": ["Lead frontend architecture decisions", "Optimize Core Web Vitals", "Build accessible components", "Mentor team members"], "benefits": ["₹30-42 LPA + RSUs", "5 days volunteering leave", "₹5L learning budget", "Flexible remote work"], "about_company": "Atlassian builds collaboration tools used by 250K+ organizations worldwide."},
        {"company": "Adobe", "role": "Computer Vision Engineer - Creative Cloud", "domain": "Data", "location": "Noida", "salary": "₹22-32 LPA", "job_type": "Full-time", "skills": ["Python", "PyTorch", "Computer Vision", "Deep Learning", "C++", "OpenCV", "GANs", "Image Processing"], "last_date_to_apply": today + timedelta(days=17), "description": "Develop AI-powered creative tools for Photoshop and Illustrator. Build generative models for content-aware fill, neural filters, and automated image enhancement features.", "eligibility": "M.Tech/PhD in CS/ML with publications preferred", "responsibilities": ["Research generative models", "Implement production CV pipelines", "Optimize inference latency", "Publish research papers"], "benefits": ["₹22-32 LPA + RSUs", "Adobe Creative Cloud free", "Conference travel", "Patent bonuses"], "about_company": "Adobe is the global leader in creative and document management solutions."},
        {"company": "Salesforce", "role": "Platform Engineer - Heroku", "domain": "Software", "location": "Hyderabad", "salary": "₹20-28 LPA", "job_type": "Full-time", "skills": ["Ruby", "Go", "PostgreSQL", "Kubernetes", "AWS", "Distributed Systems", "Linux"], "last_date_to_apply": today + timedelta(days=12), "description": "Scale Heroku's platform serving 13M+ apps. Build container orchestration systems, optimize dyno scheduling, and ensure multi-tenant isolation at massive scale.", "eligibility": "B.Tech/M.Tech CS, 4+ years platform experience", "responsibilities": ["Scale container orchestration", "Improve platform reliability", "Design multi-tenant systems", "On-call rotation"], "benefits": ["₹20-28 LPA + RSUs", "7 days volunteer time", "₹2L wellness", "Equality programs"], "about_company": "Salesforce is the world's #1 CRM platform trusted by 150K+ companies."},
        {"company": "Oracle", "role": "Database Kernel Developer", "domain": "Core", "location": "Bangalore", "salary": "₹18-25 LPA", "job_type": "Full-time", "skills": ["C", "C++", "Data Structures", "Operating Systems", "File Systems", "Concurrency", "Algorithms"], "last_date_to_apply": today + timedelta(days=22), "description": "Work on Oracle Database kernel internals powering mission-critical enterprise workloads. Optimize query execution plans, buffer cache algorithms, and REDO log performance.", "eligibility": "M.Tech CS with systems specialization, 8+ CGPA", "responsibilities": ["Optimize query execution engine", "Develop storage algorithms", "Fix concurrency bugs", "Performance benchmarking"], "benefits": ["₹18-25 LPA + bonus", "Health insurance family", "Patent incentives", "Global mobility"], "about_company": "Oracle Database is the world's most popular enterprise database."},
        {"company": "SAP", "role": "HANA Cloud Engineer", "domain": "Core", "location": "Bangalore", "salary": "₹14-20 LPA", "job_type": "Full-time", "skills": ["C++", "SQL", "Distributed Systems", "Cloud Computing", "Linux", "Memory Management", "Algorithms"], "last_date_to_apply": today + timedelta(days=19), "description": "Develop SAP HANA's in-memory database engine for cloud deployments. Work on columnar storage, query optimization, and distributed transaction processing for enterprise workloads.", "eligibility": "B.Tech/M.Tech CS, 7+ CGPA", "responsibilities": ["Develop HANA cloud features", "Optimize memory management", "Build distributed queries", "Ensure data consistency"], "benefits": ["₹14-20 LPA + bonus", "SAP Learning Hub", "Flexible work", "Global rotation program"], "about_company": "SAP is the market leader in enterprise application software."},
        {"company": "Deloitte", "role": "Technology Consultant - Digital Transformation", "domain": "Product", "location": "Mumbai", "salary": "₹12-18 LPA", "job_type": "Full-time", "skills": ["Business Analysis", "Cloud Strategy", "Agile", "Stakeholder Management", "SQL", "PowerBI", "Communication"], "last_date_to_apply": today + timedelta(days=14), "description": "Lead digital transformation initiatives for Fortune 500 clients. Translate business requirements into technology roadmaps and manage cross-functional delivery teams.", "eligibility": "B.Tech + MBA preferred, consulting experience", "responsibilities": ["Lead client workshops", "Create technology roadmaps", "Manage delivery teams", "Present to C-suite"], "benefits": ["₹12-18 LPA + bonus", "Travel allowance", "MBA sponsorship", "Rapid promotions"], "about_company": "Deloitte is one of the Big Four professional services firms globally."},
        {"company": "JP Morgan", "role": "Quantitative Developer - Equity Derivatives", "domain": "Finance", "location": "Mumbai", "salary": "₹22-32 LPA", "job_type": "Full-time", "skills": ["Python", "C++", "Quantitative Finance", "Stochastic Calculus", "NumPy", "Risk Management", "SQL"], "last_date_to_apply": today + timedelta(days=9), "description": "Build pricing and risk engines for equity derivatives desk managing $200B+ notional. Implement Monte Carlo simulations, Greeks computation, and real-time P&L systems.", "eligibility": "M.Tech/PhD in Math/Physics/CS, quantitative background", "responsibilities": ["Implement pricing models", "Build risk engines", "Optimize Monte Carlo", "Validate model accuracy"], "benefits": ["₹22-32 LPA + 40-100% bonus", "Stock purchase plan", "CFA/FRM sponsorship", "Global mobility"], "about_company": "JP Morgan is the largest bank in the US with $3.7 trillion in assets."},
        {"company": "Morgan Stanley", "role": "Technology Analyst - Fixed Income", "domain": "Finance", "location": "Mumbai", "salary": "₹14-20 LPA", "job_type": "Full-time", "skills": ["Java", "Spring", "SQL", "Fixed Income", "Agile", "Linux", "Messaging Systems"], "last_date_to_apply": today + timedelta(days=11), "description": "Build electronic trading platforms for fixed income securities. Develop low-latency order management systems processing thousands of bond trades per second.", "eligibility": "B.Tech/M.Tech CS/IT, 7+ CGPA", "responsibilities": ["Build trading platform features", "Optimize order routing", "Implement market data feeds", "Support production systems"], "benefits": ["₹14-20 LPA + bonus", "Health insurance premium", "Gym membership", "Annual learning budget"], "about_company": "Morgan Stanley is a leading global financial services firm."},
        {"company": "Deutsche Bank", "role": "Software Engineering Intern - Risk Technology", "domain": "Finance", "location": "Pune", "salary": "₹60,000/month", "job_type": "Internship", "skills": ["Python", "Java", "SQL", "Risk Management", "Data Analysis", "Git", "Agile"], "last_date_to_apply": today + timedelta(days=5), "description": "6-month internship in risk technology building regulatory reporting systems. Work with real market data to develop risk calculation engines and compliance dashboards.", "eligibility": "B.Tech 3rd/4th year CS/IT/Math, 7+ CGPA", "responsibilities": ["Develop risk calculators", "Build reporting dashboards", "Write automated tests", "Document technical designs"], "benefits": ["₹60K/month", "PPO ₹16-20 LPA", "Mentorship program", "Networking events"], "about_company": "Deutsche Bank is a leading European bank with strong technology focus."},
        {"company": "Barclays", "role": "Data Engineer - Fraud Detection", "domain": "Data", "location": "Pune", "salary": "₹12-18 LPA", "job_type": "Full-time", "skills": ["Python", "Spark", "Kafka", "SQL", "Machine Learning", "AWS", "Airflow", "Hadoop"], "last_date_to_apply": today + timedelta(days=13), "description": "Build real-time fraud detection pipelines processing millions of card transactions daily. Design streaming architectures that flag suspicious activity within milliseconds.", "eligibility": "B.Tech/M.Tech CS/IT, 6.5+ CGPA", "responsibilities": ["Build streaming pipelines", "Design fraud detection rules", "Optimize Spark jobs", "Monitor data quality"], "benefits": ["₹12-18 LPA + bonus", "Health insurance", "Pension plan", "Flexible working"], "about_company": "Barclays is a British multinational bank with major tech operations in India."},
        {"company": "NVIDIA", "role": "CUDA Engineer - Deep Learning", "domain": "Core", "location": "Bangalore", "salary": "₹25-38 LPA", "job_type": "Full-time", "skills": ["C++", "CUDA", "GPU Programming", "Deep Learning", "Linear Algebra", "Python", "Performance Optimization"], "last_date_to_apply": today + timedelta(days=18), "description": "Optimize deep learning kernels for NVIDIA GPUs powering AI workloads globally. Write CUDA code achieving 90%+ GPU utilization for transformer architectures and LLM inference.", "eligibility": "M.Tech/PhD CS with GPU/HPC experience", "responsibilities": ["Write optimized CUDA kernels", "Profile GPU workloads", "Optimize memory bandwidth", "Collaborate with research teams"], "benefits": ["₹25-38 LPA + RSUs", "Latest GPU hardware", "Conference sponsorship", "Patent bonuses"], "about_company": "NVIDIA is the world leader in accelerated computing and AI hardware."},
        {"company": "Intel", "role": "Compiler Engineer - oneAPI", "domain": "Core", "location": "Bangalore", "salary": "₹16-24 LPA", "job_type": "Full-time", "skills": ["C++", "LLVM", "Compiler Design", "x86 Architecture", "Optimization", "Python", "Assembly"], "last_date_to_apply": today + timedelta(days=21), "description": "Build Intel's oneAPI compiler toolchain enabling heterogeneous computing across CPUs, GPUs, and FPGAs. Implement optimization passes and code generation for next-gen Intel architectures.", "eligibility": "M.Tech/PhD CS with compiler/architecture background", "responsibilities": ["Implement compiler optimizations", "Develop code generators", "Write performance benchmarks", "Contribute to LLVM upstream"], "benefits": ["₹16-24 LPA + bonus", "Latest Intel hardware", "Patent incentives", "Sabbatical program"], "about_company": "Intel is a global semiconductor leader driving computing innovation."},
        {"company": "Qualcomm", "role": "Embedded Software Engineer - 5G Modem", "domain": "Core", "location": "Hyderabad", "salary": "₹14-22 LPA", "job_type": "Full-time", "skills": ["C", "C++", "RTOS", "ARM Architecture", "5G/LTE", "DSP", "Embedded Systems"], "last_date_to_apply": today + timedelta(days=15), "description": "Develop firmware for Qualcomm's 5G modem chipsets powering billions of devices. Implement protocol stack layers, optimize power consumption, and ensure carrier certification.", "eligibility": "B.Tech/M.Tech ECE/CS, 7+ CGPA", "responsibilities": ["Implement 5G protocol layers", "Optimize power consumption", "Debug hardware-software issues", "Support carrier certification"], "benefits": ["₹14-22 LPA + bonus", "Patent rewards", "Health insurance", "Flexible work"], "about_company": "Qualcomm invents breakthrough technologies powering 5G connectivity worldwide."},
        {"company": "Samsung", "role": "Android Framework Developer", "domain": "Software", "location": "Bangalore", "salary": "₹12-18 LPA", "job_type": "Full-time", "skills": ["Java", "C++", "Android AOSP", "Linux Kernel", "System Design", "Git", "Debugging"], "last_date_to_apply": today + timedelta(days=10), "description": "Customize Android framework for Samsung Galaxy devices used by 300M+ users. Develop One UI features, optimize system performance, and integrate with Samsung's hardware ecosystem.", "eligibility": "B.Tech/M.Tech CS/ECE, 7+ CGPA", "responsibilities": ["Develop One UI features", "Optimize Android framework", "Fix system-level bugs", "Collaborate with hardware teams"], "benefits": ["₹12-18 LPA + bonus", "Samsung devices", "Health insurance", "R&D lab access"], "about_company": "Samsung is the world's largest smartphone manufacturer with Galaxy ecosystem."},
        {"company": "Cisco", "role": "Network Software Engineer - SD-WAN", "domain": "Software", "location": "Bangalore", "salary": "₹14-20 LPA", "job_type": "Full-time", "skills": ["C", "Python", "Networking", "TCP/IP", "Linux", "SDN", "YANG Models", "Automation"], "last_date_to_apply": today + timedelta(days=12), "description": "Build Cisco's SD-WAN solution connecting 100K+ enterprise sites globally. Develop control plane software, implement routing protocols, and build network automation tools.", "eligibility": "B.Tech/M.Tech CS/ECE, networking fundamentals", "responsibilities": ["Develop SD-WAN control plane", "Implement routing protocols", "Build automation frameworks", "Performance testing"], "benefits": ["₹14-20 LPA + bonus", "CCIE certification sponsored", "Health insurance", "Stock purchase plan"], "about_company": "Cisco is the worldwide leader in networking and cybersecurity solutions."},
        {"company": "VMware", "role": "Cloud Infrastructure Engineer", "domain": "Core", "location": "Bangalore", "salary": "₹16-24 LPA", "job_type": "Full-time", "skills": ["Go", "Python", "Kubernetes", "vSphere", "Distributed Systems", "Linux", "Networking", "Storage"], "last_date_to_apply": today + timedelta(days=14), "description": "Build VMware's next-generation cloud infrastructure platform. Develop Kubernetes-native virtualization, implement storage orchestration, and design multi-cloud management solutions.", "eligibility": "B.Tech/M.Tech CS, 3+ years infrastructure experience", "responsibilities": ["Develop K8s operators", "Build storage orchestration", "Design cloud APIs", "Ensure platform reliability"], "benefits": ["₹16-24 LPA + RSUs", "Broadcom benefits", "Remote work", "Learning budget"], "about_company": "VMware is the leader in multi-cloud services for enterprise workloads."},
        {"company": "Nutanix", "role": "Software Engineer - Hyperconverged Storage", "domain": "Core", "location": "Bangalore", "salary": "₹18-26 LPA", "job_type": "Full-time", "skills": ["C++", "Python", "Distributed Systems", "Storage Systems", "Linux", "Paxos/Raft", "Performance Tuning"], "last_date_to_apply": today + timedelta(days=16), "description": "Build Nutanix's distributed storage fabric powering enterprise hybrid cloud. Implement consensus protocols, design data replication strategies, and optimize I/O paths for NVMe storage.", "eligibility": "B.Tech/M.Tech CS, strong systems background", "responsibilities": ["Implement consensus protocols", "Optimize storage I/O paths", "Design replication strategies", "Debug distributed systems"], "benefits": ["₹18-26 LPA + RSUs", "Health insurance premium", "₹2L learning budget", "Flexible PTO"], "about_company": "Nutanix is a leader in hyperconverged infrastructure and hybrid cloud."},
        {"company": "Freshworks", "role": "Full Stack Developer - Freshdesk", "domain": "Software", "location": "Chennai", "salary": "₹12-18 LPA", "job_type": "Full-time", "skills": ["Ruby on Rails", "React", "PostgreSQL", "Redis", "AWS", "JavaScript", "REST APIs"], "last_date_to_apply": today + timedelta(days=8), "description": "Build customer support features for Freshdesk used by 60K+ businesses globally. Develop ticketing workflows, automation rules, and real-time collaboration tools.", "eligibility": "B.Tech/M.Tech CS/IT, 6.5+ CGPA", "responsibilities": ["Build full-stack features", "Design REST APIs", "Optimize database queries", "Write automated tests"], "benefits": ["₹12-18 LPA + ESOPs", "Health insurance", "Free lunch", "Learning stipend"], "about_company": "Freshworks provides SaaS solutions used by 60K+ businesses in 120+ countries."},
        {"company": "Zoho", "role": "Product Engineer - Zoho CRM", "domain": "Product", "location": "Chennai", "salary": "₹8-14 LPA", "job_type": "Full-time", "skills": ["Java", "JavaScript", "SQL", "Product Thinking", "REST APIs", "System Design", "Agile"], "last_date_to_apply": today + timedelta(days=25), "description": "Own end-to-end product features for Zoho CRM serving 250K+ businesses. Design workflow automation, build integrations, and ship features that directly impact revenue.", "eligibility": "B.Tech/M.Tech CS/IT, 6.5+ CGPA", "responsibilities": ["Design CRM features end-to-end", "Build workflow automations", "Develop third-party integrations", "Analyze feature adoption"], "benefits": ["₹8-14 LPA", "Free meals", "Zoho University access", "No-layoff policy"], "about_company": "Zoho is a privately-held SaaS company with 80M+ users and zero external funding."},
        {"company": "Postman", "role": "Backend Engineer - API Platform", "domain": "Software", "location": "Bangalore", "salary": "₹18-26 LPA", "job_type": "Full-time", "skills": ["Node.js", "Go", "MongoDB", "AWS", "API Design", "Microservices", "Docker", "GraphQL"], "last_date_to_apply": today + timedelta(days=11), "description": "Build the API development platform used by 25M+ developers worldwide. Design collaboration features, implement API governance tools, and scale infrastructure for global usage.", "eligibility": "B.Tech/M.Tech CS, 3+ years backend experience", "responsibilities": ["Design platform APIs", "Build collaboration features", "Scale to millions of users", "Implement API governance"], "benefits": ["₹18-26 LPA + ESOPs", "Remote-first culture", "₹2L learning budget", "Home office setup"], "about_company": "Postman is the world's leading API platform used by 25M+ developers."},
        {"company": "BrowserStack", "role": "Infrastructure Engineer - Test Grid", "domain": "Software", "location": "Mumbai", "salary": "₹16-24 LPA", "job_type": "Full-time", "skills": ["Python", "Go", "Kubernetes", "AWS", "Selenium", "Docker", "Linux", "Networking"], "last_date_to_apply": today + timedelta(days=9), "description": "Scale BrowserStack's test infrastructure running 2M+ tests daily across 3000+ real devices and browsers. Build auto-scaling systems, optimize resource allocation, and ensure sub-second test startup.", "eligibility": "B.Tech/M.Tech CS, infrastructure experience preferred", "responsibilities": ["Scale test infrastructure", "Optimize resource allocation", "Build monitoring systems", "Reduce test startup time"], "benefits": ["₹16-24 LPA + ESOPs", "Health insurance", "Home office budget", "Conference sponsorship"], "about_company": "BrowserStack provides cloud testing infrastructure to 50K+ companies globally."},
        {"company": "Meesho", "role": "Machine Learning Engineer - Search & Discovery", "domain": "Data", "location": "Bangalore", "salary": "₹18-28 LPA", "job_type": "Full-time", "skills": ["Python", "TensorFlow", "NLP", "Information Retrieval", "Spark", "Deep Learning", "SQL", "MLOps"], "last_date_to_apply": today + timedelta(days=7), "description": "Build search and discovery systems for India's largest social commerce platform with 150M+ monthly users. Develop multilingual NLP models, visual search, and personalized ranking algorithms.", "eligibility": "M.Tech/PhD in CS/ML, NLP experience preferred", "responsibilities": ["Build search ranking models", "Develop multilingual NLP", "Implement visual search", "Run online experiments"], "benefits": ["₹18-28 LPA + ESOPs", "Health insurance", "Learning budget", "Flexible hours"], "about_company": "Meesho is India's largest social commerce platform empowering 15M+ entrepreneurs."},
        {"company": "Myntra", "role": "Frontend Engineer - Mobile Web", "domain": "Software", "location": "Bangalore", "salary": "₹14-20 LPA", "job_type": "Full-time", "skills": ["React", "Next.js", "TypeScript", "PWA", "Performance", "CSS", "Web Vitals"], "last_date_to_apply": today + timedelta(days=6), "description": "Optimize Myntra's mobile web experience for 50M+ monthly shoppers. Build progressive web app features, achieve sub-2s page loads, and implement engaging product discovery interfaces.", "eligibility": "B.Tech/M.Tech CS/IT, 2+ years frontend experience", "responsibilities": ["Optimize Core Web Vitals", "Build PWA features", "Implement A/B tests", "Reduce bundle sizes"], "benefits": ["₹14-20 LPA + ESOPs", "Myntra shopping credits", "Health insurance", "Flexible work"], "about_company": "Myntra is India's leading fashion e-commerce platform with 50M+ monthly users."},
        {"company": "Nykaa", "role": "Data Analyst - Growth & Marketing", "domain": "Data", "location": "Mumbai", "salary": "₹8-12 LPA", "job_type": "Full-time", "skills": ["SQL", "Python", "Google Analytics", "Tableau", "Excel", "Statistics", "A/B Testing"], "last_date_to_apply": today + timedelta(days=10), "description": "Drive data-informed growth strategies for India's largest beauty platform. Analyze customer cohorts, optimize marketing spend across channels, and build attribution models.", "eligibility": "B.Tech/MBA with analytics experience", "responsibilities": ["Build marketing dashboards", "Analyze customer cohorts", "Optimize CAC/LTV ratios", "Design A/B experiments"], "benefits": ["₹8-12 LPA + ESOPs", "Nykaa product credits", "Health insurance", "Learning programs"], "about_company": "Nykaa is India's leading beauty and lifestyle platform with 20M+ customers."},
        {"company": "Dream11", "role": "Backend Engineer - Contest Engine", "domain": "Software", "location": "Mumbai", "salary": "₹20-30 LPA", "job_type": "Full-time", "skills": ["Java", "Spring Boot", "Redis", "Kafka", "System Design", "High Concurrency", "AWS", "MySQL"], "last_date_to_apply": today + timedelta(days=3), "description": "Build contest systems handling 5M+ concurrent users during IPL matches. Design real-time leaderboard calculations, implement fair contest allocation, and ensure zero-downtime during peak traffic.", "eligibility": "B.Tech/M.Tech CS, high-scale systems experience", "responsibilities": ["Design high-concurrency systems", "Build real-time leaderboards", "Implement contest engines", "Handle 5M+ concurrent users"], "benefits": ["₹20-30 LPA + ESOPs", "Health insurance premium", "Sports event tickets", "Gaming room office"], "about_company": "Dream11 is India's biggest fantasy sports platform with 180M+ users."},
        {"company": "MPL", "role": "Game Server Engineer", "domain": "Software", "location": "Bangalore", "salary": "₹16-24 LPA", "job_type": "Full-time", "skills": ["Go", "WebSocket", "Redis", "System Design", "Networking", "Docker", "Kubernetes", "Algorithms"], "last_date_to_apply": today + timedelta(days=8), "description": "Build real-time multiplayer game servers supporting millions of concurrent players. Implement matchmaking algorithms, anti-cheat systems, and sub-100ms game state synchronization.", "eligibility": "B.Tech/M.Tech CS, real-time systems experience", "responsibilities": ["Build game servers in Go", "Implement matchmaking", "Design anti-cheat systems", "Optimize network latency"], "benefits": ["₹16-24 LPA + ESOPs", "Gaming setup provided", "Health insurance", "Flexible hours"], "about_company": "MPL is India's largest mobile gaming platform with 100M+ users."},
        {"company": "Unacademy", "role": "Video Streaming Engineer", "domain": "Software", "location": "Bangalore", "salary": "₹14-20 LPA", "job_type": "Full-time", "skills": ["Python", "FFmpeg", "HLS/DASH", "AWS MediaServices", "CDN", "WebRTC", "Docker"], "last_date_to_apply": today + timedelta(days=12), "description": "Build live streaming infrastructure supporting 100K+ concurrent learners. Optimize adaptive bitrate streaming, reduce latency to sub-3 seconds, and ensure 99.9% stream availability.", "eligibility": "B.Tech/M.Tech CS/ECE, streaming experience preferred", "responsibilities": ["Build live streaming pipeline", "Optimize adaptive bitrate", "Reduce stream latency", "Monitor stream quality"], "benefits": ["₹14-20 LPA + ESOPs", "Free course access", "Health insurance", "Learning budget"], "about_company": "Unacademy is India's largest learning platform with 60M+ registered learners."},
        {"company": "upGrad", "role": "Full Stack Engineering Intern", "domain": "Software", "location": "Mumbai", "salary": "₹40,000/month", "job_type": "Internship", "skills": ["React", "Node.js", "MongoDB", "Express", "JavaScript", "Git", "REST APIs"], "last_date_to_apply": today + timedelta(days=5), "description": "6-month internship building edtech features for 2M+ working professionals. Develop course delivery platforms, implement progress tracking, and build interactive coding environments.", "eligibility": "B.Tech 3rd/4th year CS/IT, 6.5+ CGPA", "responsibilities": ["Build course platform features", "Implement progress tracking", "Write API endpoints", "Participate in sprint planning"], "benefits": ["₹40K/month", "PPO ₹12-16 LPA", "Free upGrad courses", "Mentorship"], "about_company": "upGrad is India's largest online higher education platform for working professionals."},
        {"company": "Juspay", "role": "Haskell Developer - Payment Orchestration", "domain": "Software", "location": "Bangalore", "salary": "₹16-24 LPA", "job_type": "Full-time", "skills": ["Haskell", "Functional Programming", "PostgreSQL", "System Design", "API Design", "Docker", "AWS"], "last_date_to_apply": today + timedelta(days=14), "description": "Build payment orchestration systems in Haskell processing 50M+ transactions daily. Design type-safe APIs, implement payment routing logic, and ensure PCI-DSS compliance with functional programming.", "eligibility": "B.Tech/M.Tech CS, functional programming interest", "responsibilities": ["Write production Haskell code", "Design payment APIs", "Implement routing logic", "Ensure PCI compliance"], "benefits": ["₹16-24 LPA + ESOPs", "Health insurance", "Conference sponsorship", "Learning Fridays"], "about_company": "Juspay powers payments for India's top apps including Amazon, Flipkart, and Swiggy."},
    ]
